baseURL = 'https://sivalabs-guides.netlify.app/'
languageCode = 'en-us'
title = 'SivaLabs Tech Guides'
theme = 'ananke'

[params]
    custom_css = ["molokai.css","custom.css"]

[markup]
    [markup.asciidocExt]
        backend = 'html5'
        extensions = []
        failureLevel = 'fatal'
        noHeaderOrFooter = true
        preserveTOC = false
        safeMode = 'unsafe'
        sectionNumbers = false
        trace = false
        verbose = false
        workingFolderCurrent = false
        [markup.asciidocExt.attributes]
            allow-uri-read = ""
            source-highlighter = "rouge"
            rouge-style = "molokai"
            icons = "font"

[security]
    enableInlineShortcodes = false

[security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']

[security.funcs]
    getenv = ['^HUGO_', '^CI$']

[security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']